/* final_extra_offsets.h
 * Verified static offsets/signatures extracted from iPad8,9 iOS 17.3.1 kernelcache
 * Generated by static ADRP/ADD + string scans in the workspace.
 * Each entry: VM address, file offset (in decompressed kernelcache), 32-byte hex signature.
 */
#ifndef FINAL_EXTRA_OFFSETS_H
#define FINAL_EXTRA_OFFSETS_H

// AMFI global (AMFI struct base) in __DATA_CONST
#define AMFI_VM 0xfffffff007c86ae0ULL
#define AMFI_FILEOFF 0x0c82ae0
static const unsigned char AMFI_SIG32[32] = {
  0x24,0xb1,0x35,0x01,0x8d,0xd7,0x11,0x80,0x58,0xb0,0x35,0x01,0x1d,0x3a,0x11,0x80,
  0x6c,0xaf,0x35,0x01,0x90,0xa3,0x11,0x80,0xb4,0xae,0x35,0x01,0x0b,0x24,0x11,0x80
};
// Found: parsed symbol and signature entry in offsets_generated_iPad8_9_17_3_1.json

// AMFI cs_enforcement_disable string occurrence (string found in kext/kernelcache)
// This locates the textual message "cs_enforcement_disable" inside the decompressed kernelcache.
#define AMFI_CS_ENFORCEMENT_DISABLE_STR_VM 0xfffffff007410e50ULL
#define AMFI_CS_ENFORCEMENT_DISABLE_STR_FILEOFF 0x40ce50
static const unsigned char AMFI_CS_ENFORCEMENT_DISABLE_STR_SIG32[32] = {
  0x63,0x73,0x5f,0x65,0x6e,0x66,0x6f,0x72,0x63,0x65,0x6d,0x65,0x6e,0x74,0x5f,0x64,
  0x69,0x73,0x61,0x62,0x6c,0x65,0x00,0x25,0x73,0x3a,0x20,0x63,0x73,0x5f,0x65,0x6e
};
// Found by scanning the decompressed kernelcache for the ASCII string "cs_enforcement_disable".

// Trust-cache related string occurrence (static string reference)
#define TRUST_CACHE_STR_VM 0xfffffff0070489bbULL
#define TRUST_CACHE_STR_FILEOFF 0x449bb
static const unsigned char TRUST_CACHE_STR_SIG32[32] = {
  0x74,0x72,0x75,0x73,0x74,0x5f,0x63,0x61,0x63,0x68,0x65,0x5f,0x69,0x6e,0x69,0x74,
  0x00,0x4f,0x53,0x4b,0x65,0x78,0x74,0x52,0x65,0x6d,0x6f,0x76,0x65,0x4b,0x65,0x78
};
// Found by searching the kernelcache for the ASCII token "trust_cache" (static string occurrence).

// VFS helper string occurrences and signatures (static string locations).
// Note: these are the string occurrences found in the decompressed kernelcache; further ADRP/ADD xref
// resolution is required to map these to exact function prologues if needed.

#define VN_OPEN_STR_VM 0xfffffff00705ebddULL
#define VN_OPEN_STR_FILEOFF 0x05abdd
static const unsigned char VN_OPEN_STR_SIG32[32] = {
  0x76,0x6e,0x5f,0x6f,0x70,0x65,0x6e,0x5f,0x61,0x75,0x74,0x68,0x28,0x29,0x20,0x40,
  0x25,0x73,0x3a,0x25,0x64,0x00,0x57,0x68,0x79,0x20,0x61,0x6d,0x20,0x49,0x20,0x74
};

#define VNODE_PUT_STR_VM 0xfffffff00705de81ULL
#define VNODE_PUT_STR_FILEOFF 0x059e81
static const unsigned char VNODE_PUT_STR_SIG32[32] = {
  0x76,0x6e,0x6f,0x64,0x65,0x5f,0x70,0x75,0x74,0x28,0x25,0x70,0x29,0x3a,0x20,0x69,
  0x6f,0x63,0x6f,0x75,0x6e,0x74,0x20,0x3c,0x20,0x31,0x20,0x40,0x25,0x73,0x3a,0x25
};

#define VFS_CONTEXT_CURRENT_STR_VM 0xfffffff00a3b6c5dULL
#define VFS_CONTEXT_CURRENT_STR_FILEOFF 0x33b2c5d
static const unsigned char VFS_CONTEXT_CURRENT_STR_SIG32[32] = {
  0x76,0x66,0x73,0x5f,0x63,0x6f,0x6e,0x74,0x65,0x78,0x74,0x5f,0x63,0x75,0x72,0x72,
  0x65,0x6e,0x74,0xd1,0x00,0x04,0x21,0x5b,0x5f,0x10,0x13,0x5f,0x76,0x66,0x73,0x5f
};

/*
 * NOTES / Method summary:
 * - `AMFI_*` entry: found from parsed symbol data in offsets_generated_iPad8_9_17_3_1.json
 *   and verified by reading 32 bytes at the reported file offset in the decompressed kernelcache.
 * - `AMFI_CS_ENFORCEMENT_DISABLE_STR_*`: located by searching the decompressed kernelcache binary
 *   for the ASCII token "cs_enforcement_disable"; file offset and VM computed via the segments mapping
 *   from offsets_iPad8_9_17.3.1.json.
 * - `TRUST_CACHE_STR_*`, `VN_*_STR_*`, `VNODE_PUT_STR_*`, `VFS_CONTEXT_CURRENT_STR_*`: located by
 *   binary search for their ASCII occurrences in the decompressed kernelcache and translated
 *   to VM addresses via the segment table; 32-byte signatures are the raw 32 bytes at those file offsets.
 *
 * Next steps (recommended): run ADRP/ADD xref scans over __PRELINK_TEXT and kext regions to resolve
 * these string occurrences to the exact function prologues (vn_open/vn_write/vn_close) and to locate
 * the `cs_enforcement_disable` field within the `amfi` struct (if it is accessed via ADRP+LDR from kernel text).
 */

/* Verification status keys
 * HIGH: direct symbol/signature match or parsed symbol present
 * MEDIUM: strong static candidate (string + proximate code), but no direct memory/call XREF
 * MISSING: not found via ADRP/ADD or MOVZ/MOVK static scans
 */
#define STATUS_HIGH 3
#define STATUS_MEDIUM 2
#define STATUS_MISSING 1

/* Verification results summary (updated after MOVZ/MOVK scan): */

// AMFI struct base: parsed symbol -> HIGH
#define AMFI_VERIFIED_STATUS STATUS_HIGH

// cs_enforcement_disable field: NOT resolved to a struct offset via static MOVZ/MOVK/ADRP+LDR scans
// Reason: no direct LDR/STR using a reconstructed AMFI base register was found; field offset requires
// either ADRP+LDR xref or runtime validation. Marked MISSING for offset.
#define AMFI_CS_ENFORCEMENT_DISABLE_OFFSET_NOT_FOUND 1
#define AMFI_CS_ENFORCEMENT_DISABLE_STATUS STATUS_MISSING

// TrustCache global / kern_trustcache: not found via ADRP/ADD or MOVZ/MOVK static scans
// We have a TRUST_CACHE string occurrence (above), but no code XREF loading a global address was found.
#define KERN_TRUSTCACHE_STATUS STATUS_MISSING

// VFS functions: only string occurrences found for vn_open/vnode_put; no prologue XREF resolved
// via ADRP/ADD or MOVZ/MOVK. Mark as MEDIUM (string match) until function prologues are resolved.
#define VN_OPEN_STATUS STATUS_MEDIUM
#define VNODE_PUT_STATUS STATUS_MEDIUM
#define VFS_CONTEXT_CURRENT_STATUS STATUS_MEDIUM

/* Summary of why some items are MISSING:
 * - Modern iOS kernels / kexts often use MOVZ/MOVK, ADRP/ADD, LDR literal, or GOT indirections.
 * - I scanned for ADRP+ADD/LDR and for MOVZ/MOVK sequences; the MOVZ/MOVK reconstruction produced no
 *   candidates that were subsequently used by LDR/STR/BLR to access the AMFI or TrustCache addresses.
 * - Possible causes: addresses are constructed via MOVN/MOVZ pairs placed across non-contiguous locations,
 *   accessed via GOT/PLT-like indirection, or loaded from kext-specific literal pools that didn't produce
 *   direct ADRP/ADD patterns in __TEXT_EXEC.
 */

#endif /* FINAL_EXTRA_OFFSETS_H */
